<?PHP
	include 'header.php';
?>
<!DOCTYPE html>
<html>
	<body>
	<div style="margin-top: 200px;">
		<span style="min-width: 10%; max-width:30%; float:left;">
			<img src="http://vignette4.wikia.nocookie.net/himym/images/8/83/Rc0JG.jpg/revision/latest?cb=20130113174854">
		</span>
		<span style="float: left; max-width: 65%;">Before the start of the series and before he met the rest of the gang, Barney was somewhat of a hippie. He wanted to join the Peace Corps, was disgusted when men treated women like objects, and wished to wait to lose his virginity to his college girlfriend, Shannon, until after the two married. His personality radically changed when he caught Shannon cheating on him with a man named Greg. His current mannerisms and dress sense are based on the man who took Shannon away from him. Barney is now an extreme womanizer, not content unless he is pursuing his latest conquest. He has no problem lying or using extremely ridiculous methods to charm women. Along with being proud and very open about his collection of pornography, he doesn't see anything wrong about secretly video taping and taking pictures of the women he sleeps with. He did mention to Robin that he watches the videos to study himself more, like how athletes study game tapes. He also seems to dislike the idea of owning a "little, black book" and instead has a scrapbook filled with the pictures of women he has slept with. Barney does not care at all what happens to his one-night stands as long as he doesn't have to see or talk to them again.

In The Drunk Train, it is mentioned that Barney may have attended MIT (Massachusetts Institute of Technology) and displays a working knowledge of advanced mathematics.

Barney is very driven to achieve what he wants and will go to great lengths to make it happen. He takes comments such as "No one can do this" as a challenge, announcing "Challenge Accepted!". He will even take an entire year to fulfill a challenge even if the person who "challenged" him doesn't even remember, as seen when Barney took a year to get Ted to grow a mustache in Ten Sessions. Barney even has a gambling problem that he cultivated after Marshall made a bet with him one Super Bowl Sunday revealed in Monday Night Football. He frequently makes bets and tries to make them for exorbitant sums of money until the others remind him that it's ridiculous. In Atlantic City, it's shown that he once blew his life savings on gambling.

Barney is also shown to be very persuasive at times. In Cleaning House, he managed to talk the rest of the group into helping him pack up the stuff at his childhood house as a two-day job despite the others claiming there is no way he could talk them into it. This is also shown by his history of seducing women with fake, even ridiculous, aliases including Barack Obama Jr. or Neil Armstrong, and according to him, getting a stripper to pay him for a lap dance. However, he does not always succeed, as he fails in getting out of a speeding ticket despite numerous deliberate attempts whereas the other members of the gang have done so.

Regardless of this change, Barney has shown to have a somewhat childish personality as well. He is an avid blogger and laser tag fan. He's extremely aggressive while playing laser tag, to the point where he's been seen pinning a child down to the ground while shooting him, which got him banned from his usual laser tag spot. To add to his childish personality, he sought revenge by TP'ing the place for banning him. He loves to do magic tricks, a trait he shares with his father, but he usually uses them to pick up women. Barney seems to have a preference with magic that involves fire, which caused his friends to have an intervention to get him to stop to using magic. Barney is known to be a huge momma's boy. James, Barney's older brother, told the rest of the gang that Barney always believed in every lie their mother told them as children, no matter how ridiculous. Barney's love for his mother goes so far that when he thought she was dying he hired a child actor and actress to pose as his son and wife and continued this lie for years to make her happy.

Barney is often shown to be ignorant of popular culture. In Woooo!, Barney and Marshall compare themselves to Mad Men, but when Marshall makes a comment that Barney smacking a secretary would be exactly what they would do in the show, Barney replies "What show?" Similarly, in Now We're Even, Barney claims to have attempted to "Inception" Lily for the preceding five years, but is completely unaware of the fact that there is a movie describing what Barney claims to have attempted to do, let alone the fact that it was released two years prior to the events of the episode.

Barney's more tender, former personality has not entirely disappeared, however. He is very loyal to his family and friends. This is shown as he acted as Ted's wingman for the entire series and helped Marshall get a job when he had financial troubles. Also, Barney comforts Robin at the end of Sandcastles in the Sand when her former boyfriend, Simon breaks up with her again. Though, he does sometimes get embarrassed when others see his kindness and will often make a rude comment to throw them off or try to keep his actions secret, as seen when he tried to stop Lily from revealing to Marshall that he went to San Francisco to convince her to return to New York and get back together with Marshall after she left him for an art fellowship.

Everyone else in the gang has noted that Barney has some very unusual and annoying habits. In Spoiler Alert, they told Barney that he'll sometimes talk in a weird, high pitched voice, use lame catchphrases, and space out and not pay attention to anyone else. Some of the catchphrases Barney uses are "Suit Up!", "It's going to be legen- wait for it... .dary!", and "Awesome". Ted has told Barney that he's too liberal with the word "legendary". In Robin 101, after Ted asked Barney whether or not he was the worst student ever when he was in school, Barney said he was told that he "had A.D... something" before asking again if they could have class outside, meaning that he probably suffers from Attention Deficit Disorder. Another odd habit that only Ted has pointed out is that when ever making up statistics, Barney tends to use the number 83, or some variation thereof (8.3 seconds in Ten Sessions). Barney also has an interesting way of watching movies. When watching, he decides who the protagonist of the movie is based on the title of the movie, for example he roots for the Terminator in The Terminator and was sad when watching the ending where it was destroyed. Similarly, he considers William Zabka the "real Karate Kid".</span>
		</div>
	</body>
</html>